config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  get 'configuration/index'
  get 'analized_site/index'
  devise_for :users
  get 'scan_urls/index'
  root 'scan_urls#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/analized_site_controller.rb
class AnalizedSiteController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/configuration_controller.rb
class ConfigurationController < ApplicationController
  def index
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/scan_urls_controller.rb
class ScanUrlsController < ApplicationController
  def index
  end
end

app/helpers/analized_site_helper.rb
module AnalizedSiteHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/configuration_helper.rb
module ConfigurationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/scan_urls_helper.rb
module ScanUrlsHelper
end

app/views/analized_site/index.html.erb
<%= render "layouts/app_header.html.erb" %>

<%= link_to raw('<i class="material-icons">arrow_back</i>'), dashboard_index_path, class: 'btn-floating btn-small waves-effect waves-light deep-orange darken-2' %>
<h1>Test</h1>

app/views/configuration/index.html.erb
<%= render "layouts/app_header.html.erb" %>

<div class="row">
  <div class="col s8 offset-s2">
    <div class="row">
      <div class="col s12">
        <div class="card  grey lighten-5">
          <div class="card-content white-text">
            <span class="card-title black-text">Configuration</span>

            <div class="row">
              <form class="col s12">
                <div class="row">
                  <div class="input-field col s12">
                    <i class="material-icons prefix">account_circle</i>
                    <input id="icon_prefix" type="text" class="validate">
                    <label for="icon_prefix">Username</label>
                  </div>
                </div>
                <div class="row">
                  <div class="input-field col s12">
                    <i class="material-icons prefix">phone</i>
                    <input id="icon_telephone" type="tel" class="validate">
                    <label for="icon_telephone">Password</label>
                  </div>
                </div>
                <div class="row">
                  <div class="col s12 center">
                    <button class="btn waves-effect waves-light orange darken-4" type="submit" name="action">Save changes
                      <i class="material-icons right white-text">save</i>
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </div>
          <div class="card-action center">
            <p class="">Cancel account?</p>
            <%= link_to 'Cancel Account', destroy_user_session_path, method: :delete, class: "btn-flat" %>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/dashboard/index.html.erb
<%= render "layouts/app_header.html.erb" %>

<%= javascript_include_tag 'dashboard' %>
<div class="row">
  <div class="col s10 offset-s1">
    <div class="col s4">
      <div class="card  grey lighten-5">
        <div class="card-content white-text">
          <span class="card-title black-text">Websites</span>

          <div class="row">
            <h4 class="black-text center">120</h4>
          </div>

        </div>

      </div>
    </div>

    <div class="col s4">
      <div class="card  grey lighten-5">
        <div class="card-content white-text">
          <span class="card-title black-text">Completed Scans</span>

          <div class="row">
            <h4 class="black-text center">200</h4>
          </div>

        </div>

      </div>
    </div>

    <div class="col s4">
      <div class="card  grey lighten-5">
        <div class="card-content white-text">
          <span class="card-title black-text">Active Vulnerabilities</span>

          <div class="row">
            <h4 class="black-text center">430</h4>
          </div>

        </div>

      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col s10 offset-s1">
    <div class="col s8">
      <div class="card  grey lighten-5">
        <div class="card-content white-text">
          <span class="card-title black-text">Active Vulnerabilities</span>

          <div id="container"></div>


        </div>

      </div>
    </div>
    <div class="col s4">
      <div class="card  grey lighten-5">
        <div class="card-content white-text">
          <span class="card-title black-text">Scans</span>


          <div class="collection">
            <%= link_to 'https://nearsoft.com', analized_site_index_path, class: "collection-item" %>
            <%= link_to 'https://facebook.com', analized_site_index_path, class: "collection-item" %>
            <%= link_to 'https://google.com', analized_site_index_path, class: "collection-item" %>
          </div>


        </div>

      </div>
    </div>
  </div>
</div>

app/views/layouts/_app_header.html.erb
<nav class="nav-extended">
  <div class="nav-wrapper light-blue darken-4">
    <a href="#" class="brand-logo">Vulnerability Scanner</a>
    <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><%= link_to raw('<i class="material-icons white-text">exit_to_app</i>'), destroy_user_session_path, method: :delete %></li>
    </ul>
  </div>
  <div class="row light-blue darken-1">
    <div class="col s12">
      <ul class="tabs tabs-transparent">
        <li class="tab col s4 <%= 'active' if current_page?(scan_urls_index_path) %>"><%= link_to raw('<i class="material-icons white-text">search</i>'), scan_urls_index_path %></li>
        <li class="tab col s4 <%= 'active' if current_page?(dashboard_index_path) %>"><%= link_to raw('<i class="material-icons white-text">history</i>'), dashboard_index_path %></li>
        <li class="tab col s4 <%= 'active' if current_page?(configuration_index_path) %>"><%= link_to raw('<i class="material-icons white-text">build</i>'), configuration_index_path %></li>
      </ul>
    </div>
  </div>
</nav>

<ul class="sidenav" id="mobile-demo">
  <li><a href="sass.html"><i class="material-icons white-text">exit_to_app</i></a></li>
</ul>

app/views/layouts/_login_header.html.erb
<nav>
    <div class="nav-wrapper light-blue darken-4">
        <a href="#" class="brand-logo center">Vulnerability Scanner</a>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecurityAnalizerOWASP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scan_urls/index.html.erb
<%= render "layouts/app_header.html.erb" %>

<div class="row">
  <div class="col s8 offset-s2">
    <div class="row">
      <div class="col s12">
        <div class="card  grey lighten-5">
          <div class="card-content white-text">
            <span class="card-title black-text">Add URLs</span>
            <div class="row">
              <form class="col s12">
                <div class="row">
                  <div class="col s6"  style="overflow-y: scroll; height:200px;">
                      <% (1..6).each do |i| %>
                      <div class="input-field">
                        <i class="material-icons prefix">link</i>
                        <input id="url" type="text" class="validate">
                        <label for="url">Url<% i %></label>
                      </div>
                      <% end %>
                  </div>
                  <div class="col s1">
                    <a class="btn-floating btn-small waves-effect waves-light red"><i class="material-icons">add</i></a>
                  </div>
                  <div class="col s5">
                    <div class="row">
                      <div class="col s6">
                        <p>
                          <label>
                            <input type="checkbox"/>
                            <span>XSS</span>
                          </label>
                        </p>
                      </div>
                      <div class="col s6"><p>
                        <label>
                          <input type="checkbox"/>
                          <span>A2</span>
                        </label>
                      </p>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col s6">
                        <p>
                          <label>
                            <input type="checkbox"/>
                            <span>A3</span>
                          </label>
                        </p>
                      </div>
                      <div class="col s6"><p>
                        <label>
                          <input type="checkbox"/>
                          <span>A4</span>
                        </label>
                      </p>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col s6">
                        <p>
                          <label>
                            <input type="checkbox"/>
                            <span>A5</span>
                          </label>
                        </p>
                      </div>
                      <div class="col s6"><p>
                        <label>
                          <input type="checkbox"/>
                          <span>A6</span>
                        </label>
                      </p>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col s6">
                        <p>
                          <label>
                            <input type="checkbox"/>
                            <span>A7</span>
                          </label>
                        </p>
                      </div>
                      <div class="col s6"><p>
                        <label>
                          <input type="checkbox"/>
                          <span>A8</span>
                        </label>
                      </p>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col s6">
                        <p>
                          <label>
                            <input type="checkbox" class="checkbox-orange"/>
                            <span>A9</span>
                          </label>
                        </p>
                      </div>
                      <div class="col s6"><p>
                        <label>
                          <input type="checkbox" class="checkbox-orange"/>
                          <span>A10</span>
                        </label>
                      </p>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col s12 center">
                    <button class="btn waves-effect waves-light orange darken-4" type="submit" name="action">Scan
                      <i class="material-icons right white-text">search</i>
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>